version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: samsuapi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aa123456
      MYSQL_DATABASE: samsu
      MYSQL_USER: huytna
      MYSQL_PASSWORD: Aa123456
    ports:
      - '3307:3306'
    networks:
      - samsuapi-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Aa123456 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  application:
    container_name: samsuapi-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - samsuapi-network
    depends_on:
      - db
networks:
  samsuapi-network:
    name: samsuapi-network
    driver: bridge
