spring:
  datasource:
    url: jdbc:mysql://pi.nhalq.dev:2500/samsu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #    url: jdbc:mysql://localhost:3306/samsu?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 233487864072-ldpmp56m9cr11utl8ev17l94a5jf63h9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8081/api/auth/callback/login-google
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo?access_token=
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token

app:
  jwtSecret: samsu-capstone
  jwtExpirationInMs: 604800000

cors:
  allowedOrigins: '*'

server:
  port: 8081
  error:
      include-stacktrace=never