name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: thienduc12311/samsu-backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
  deploy:
      
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Deploy to DigitalOcean Droplet
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USERNAME}}
            key: ${{secrets.SSH_KEY}}
            script: |
              docker pull thienduc12311/samsu-backend
              docker rm -f samsu-backend
              docker run -d --name samsu-backend -p 8081:8081 thienduc12311/samsu-backend
              echo 'Deployment to digital ocean finished'
